# Generated by Django 5.2.4 on 2025-07-27 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Propiedad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio (USD)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
